r: 0.05
x_t_2n: 20.0 # x for 2n
x_t_2n_1: 20.0 # x for 2n+1
p_k_2n: 1.0 # p for 2n
p_k_2n_1: 1.0 # p for 2n+1
q_2n: 0.001 # q for 2n
q_2n_1: 0.001 # q for 2n+1
q: 0.001 # q upto 2n
diagnostics: true # true for on, false for off
online_tune: true # true for tuning, false for not